import { Page } from './PublicLayout'

const company = 'Stranerd Academy Limited (RC 1674339)'
const email = 'officialstranerd@gmail.com'

function LegalShell({ title, intro, children }: { title: string; intro: string; children: React.ReactNode }) {
  return <Page><main className="legal-document"><header><span className="eyebrow">Effective 6 August 2026</span><h1>{title}</h1><p>{intro}</p></header><article>{children}</article><footer><h2>Contact us</h2><p>{company}<br />No 23 Alhaji Kosoko Road, Berger, Lagos, Nigeria<br /><a href={`mailto:${email}`}>{email}</a></p></footer></main></Page>
}

function PrivacyPolicy() {
  return <LegalShell title="Privacy policy" intro="This policy explains how Stranerd handles personal data when you use our website, anatomy learning application, account features, AI tools, and paid services.">
    <section><h2>1. Who controls your data</h2><p>{company} is the data controller for Stranerd. We operate from Lagos, Nigeria and process personal data under the Nigeria Data Protection Act 2023 and other applicable laws.</p></section>
    <section><h2>2. Information we collect</h2><p>When you sign in with Google, we receive your Google account identifier, name, email address, profile image, and authentication information. We store your Stranerd profile, credit balances, credit transactions, subscription status, purchase records, and AI feature usage.</p><p>When you explicitly use an AI feature, we process the question, selected anatomy context, model context, and technical information needed to return a response. Guest notes and local learning settings currently remain in your browser unless a feature clearly states otherwise.</p><p>We also receive ordinary technical data such as browser type, device information, IP address, request timestamps, security logs, and limited product analytics. Spotflow processes checkout and payment information. Stranerd does not receive or store your full payment-card details.</p></section>
    <section><h2>3. How we use information</h2><ul><li>Provide accounts, learning features, credits, subscriptions, purchases, and support.</li><li>Authenticate users, prevent fraud, secure the service, and investigate abuse.</li><li>Process explicit AI requests and measure credit usage.</li><li>Reconcile payments, renewals, cancellations, refunds, and financial records.</li><li>Improve reliability and understand aggregate product usage without sending raw AI prompts or payment identifiers to analytics.</li><li>Comply with legal, tax, accounting, and regulatory obligations.</li></ul></section>
    <section><h2>4. Legal grounds</h2><p>We process data where necessary to perform our contract with you, comply with law, pursue legitimate interests such as security and service improvement, and obtain consent where required. You may withdraw consent without affecting processing that was already lawful.</p></section>
    <section><h2>5. Service providers and transfers</h2><p>We use Google for sign-in, Supabase for authentication and database services, Vercel for application hosting and analytics, Microsoft Azure OpenAI for requested AI responses, and Spotflow for payments. These providers process data under their own terms and our service arrangements. Their infrastructure may process data outside Nigeria. We use appropriate contractual and organizational protections where cross-border safeguards are required.</p></section>
    <section><h2>6. AI requests</h2><p>AI is used only after you take an explicit AI action. Relevant prompts and learning context are sent to our configured AI provider to generate a response. Do not submit confidential patient information, medical records, or another person's sensitive data. AI responses may be inaccurate and are not medical advice.</p></section>
    <section><h2>7. Cookies and local storage</h2><p>We use browser storage and authentication cookies or tokens to maintain sessions, save local preferences, notes, bookmarks, and learning state, and protect account access. Essential storage is required for signed-in features. Analytics settings will be reviewed before non-essential tracking is enabled.</p></section>
    <section><h2>8. Retention and deletion</h2><p>We retain account information while your account is active and as needed to provide the service. Verified deletion requests are normally completed within 30 days. We may retain limited payment, ledger, security, fraud-prevention, and legal records for longer where law or legitimate audit requirements require it. Retained records are restricted and no longer used for ordinary product activity.</p></section>
    <section><h2>9. Your rights</h2><p>Subject to applicable law, you may request access, correction, deletion, restriction, objection, or portability of your personal data and may withdraw consent. You may also complain to the Nigeria Data Protection Commission. We may verify your identity before completing a request.</p></section>
    <section><h2>10. Age requirement</h2><p>Stranerd accounts are available only to people aged 18 or older at launch. We do not knowingly create accounts for children. Contact us if you believe a person under 18 has provided personal data.</p></section>
    <section><h2>11. Security and changes</h2><p>We use access controls, encrypted connections, server-controlled billing and credit operations, and audit records designed to protect data. No internet service can guarantee absolute security. We may update this policy and will publish the effective date and provide additional notice where required.</p></section>
  </LegalShell>
}

function TermsOfService() {
  return <LegalShell title="Terms of service" intro="These terms govern access to Stranerd. By creating an account, purchasing credits, or using paid features, you agree to them.">
    <section><h2>1. Provider and eligibility</h2><p>Stranerd is provided by {company}. You must be at least 18 years old and legally able to enter a contract. You are responsible for the Google account used to access Stranerd and for activity under your session.</p></section>
    <section><h2>2. Educational service</h2><p>Stranerd provides interactive anatomy models, activities, quizzes, notes, dissection tools, and optional AI-generated educational responses. Content is provided for learning and general information. It is not medical advice, diagnosis, treatment, professional training certification, or a substitute for qualified clinical guidance.</p></section>
    <section><h2>3. AI limitations</h2><p>AI output may be incomplete, inaccurate, or outdated. You must verify important information using reliable academic or professional sources. Do not use AI output to make clinical decisions or submit confidential patient information.</p></section>
    <section><h2>4. Accounts</h2><p>Google is the only supported sign-in provider at launch. You must provide accurate information, protect access to your Google account, and notify us of suspected unauthorized use. We may restrict or suspend accounts used fraudulently or in breach of these terms.</p></section>
    <section><h2>5. Free and paid credits</h2><p>A new eligible account receives 20 one-time signup credits. Stranerd Plus costs NGN 2,500 per month and provides 500 subscription credits after each verified successful billing cycle. Subscription credits replace the previous cycle's subscription balance rather than accumulating. A NGN 500 PAYG pack provides 100 purchased credits that do not expire.</p><p>Credits are used in this order: free credits, current subscription credits, then purchased credits. Credits have no cash value, cannot be transferred, and may be used only for eligible Stranerd features. Failed or invalid AI operations should result in no net credit charge.</p></section>
    <section><h2>6. Billing and cancellation</h2><p>Payments are processed through Spotflow. Subscriptions renew monthly until cancelled. The renewal price and frequency are shown before checkout. Cancellation prevents future renewal and preserves paid access until the current billing period ends, unless law or provider behavior requires otherwise. Failed payments grant no credits.</p></section>
    <section><h2>7. Refunds</h2><p>Refund eligibility is governed by our <a href="/legal/refunds">Refund and cancellation policy</a>. Subscription charges may be refunded when requested within seven days and none of that billing cycle's subscription credits have been used. PAYG credit packs are generally non-refundable. Statutory consumer rights remain unaffected.</p></section>
    <section><h2>8. Acceptable use</h2><p>You must not attempt to bypass credit enforcement, probe or disrupt the service, access another user's data, automate abusive traffic, reverse engineer protected systems, upload malicious material, infringe rights, resell accounts or credits, or use Stranerd unlawfully.</p></section>
    <section><h2>9. Your content</h2><p>You retain rights in notes and prompts you create. You grant us a limited right to process that content only as needed to provide, secure, support, and improve the requested service. You are responsible for ensuring you have the right to submit content and that it contains no prohibited confidential information.</p></section>
    <section><h2>10. Intellectual property</h2><p>Stranerd's software, branding, interfaces, authored educational material, and licensed assets are protected by intellectual-property law. We grant you a limited, personal, non-exclusive, non-transferable right to use the service for lawful educational purposes while these terms apply.</p></section>
    <section><h2>11. Availability and termination</h2><p>We may modify, maintain, suspend, or discontinue features. We do not guarantee uninterrupted availability. You may stop using Stranerd or request account deletion. We may suspend or terminate access for material breaches, security threats, fraud, or legal requirements.</p></section>
    <section><h2>12. Disclaimers and liability</h2><p>To the extent permitted by law, Stranerd is provided without warranties beyond those that cannot legally be excluded. We are not responsible for decisions made in reliance on educational or AI content. Our liability will not be excluded where exclusion is prohibited by applicable law.</p></section>
    <section><h2>13. Governing law</h2><p>These terms are governed by the laws of the Federal Republic of Nigeria. Disputes are subject to the competent courts of Lagos State, after the parties first attempt good-faith resolution.</p></section>
    <section><h2>14. Changes</h2><p>We may update these terms as the service changes. Material changes will be communicated where required. Continued use after the effective date means you accept the updated terms.</p></section>
  </LegalShell>
}

function RefundPolicy() {
  return <LegalShell title="Refund and cancellation policy" intro="This policy describes subscription cancellations, subscription refund eligibility, and PAYG credit-pack treatment.">
    <section><h2>1. Subscription cancellation</h2><p>You may cancel Stranerd Plus through your account when cancellation becomes available or by contacting support. Cancellation stops future renewals. Your paid subscription remains available through the end of the current billing period. Cancellation alone does not automatically refund the current period.</p></section>
    <section><h2>2. Subscription refunds</h2><p>You may request a refund within seven calendar days of an initial subscription charge or renewal charge only if none of the 500 subscription credits allocated for that billing cycle have been used. If any credits from that cycle have been used, the charge is non-refundable except where required by law.</p><p>When a refund is approved, access and unused subscription credits associated with that charge may be removed. Refunds are returned through the original payment method and timing depends on Spotflow, your bank, and payment networks.</p></section>
    <section><h2>3. PAYG credit packs</h2><p>PAYG credit packs are non-refundable, including when credits remain unused. Purchased credits do not expire and remain available in your account. We will investigate duplicate charges, unauthorized payments, incorrect allocations, and verified technical failures. This does not limit rights that cannot be excluded under applicable consumer law.</p></section>
    <section><h2>4. Failed or cancelled payments</h2><p>A failed, abandoned, or cancelled checkout grants no credits. Browser redirect pages are informational; credits are granted only after Stranerd verifies payment server-to-server. If payment was taken but credits were not allocated, contact support for reconciliation.</p></section>
    <section><h2>5. How to request a refund</h2><p>Email <a href={`mailto:${email}`}>{email}</a> from the address associated with your Stranerd account. Include the payment date, product, amount, and provider reference. Never send full card details, passwords, secret keys, or one-time codes.</p><p>We may request information needed to verify the account and transaction. Approved requests are submitted to the payment provider promptly, but final settlement time is controlled by the provider and financial institution.</p></section>
    <section><h2>6. Chargebacks and abuse</h2><p>Please contact us first so we can investigate. Fraudulent refund requests, payment disputes after credits have been consumed, or abuse of checkout systems may result in account restriction while the matter is reviewed.</p></section>
  </LegalShell>
}

export function LegalPage({ path }: { path: string }) {
  if (path === '/legal/privacy') return <PrivacyPolicy />
  if (path === '/legal/terms') return <TermsOfService />
  return <RefundPolicy />
}
