import type { Evaluation, Lesson, LessonState } from '../types'

export function evaluateExact(targetIds: string[], state: LessonState): Evaluation {
  const expected = [...targetIds].sort()
  const selected = [...new Set(state.selectedIds)].sort()
  const pass = expected.length === selected.length && expected.every((id, index) => id === selected[index])
  return {
    pass,
    detail: pass
      ? `selected = ${selected.join(' + ')}`
      : `selected = ${selected.join(' + ') || 'none'}; expected ${expected.join(' + ')}`,
  }
}

type TaskInput = Pick<Lesson, 'title' | 'prompt' | 'targetIds' | 'fallback'> & { hints?: string[] }

const makeLessons = (modelId: string, tasks: TaskInput[]): Lesson[] => tasks.map((task, index) => ({
  ...task,
  id: `${modelId}-${String(index + 1).padStart(2, '0')}`,
  hints: task.hints ?? ['Use the structure labels and the model facts to identify the authored marker.'],
  evaluate: (state) => evaluateExact(task.targetIds, state),
}))

export const lessonsByModel: Record<string, Lesson[]> = {
  heart: makeLessons('heart', [
    { title: 'Systemic outflow', prompt: 'Select the vessel that receives blood directly from the left ventricle.', targetIds: ['aorta'], hints: ['Trace flow away from the chamber with the thickest wall.', 'Look superiorly for the large arching artery.'], fallback: 'The ascending aorta receives oxygenated blood through the aortic valve. Its elastic wall buffers the pressure pulse generated by left-ventricular systole.' },
    { title: 'Pressure chamber', prompt: 'Identify the chamber that generates systemic arterial pressure.', targetIds: ['left-ventricle'], hints: ['Compare the workload of pulmonary and systemic circuits.', 'Select the inferior chamber forming much of the cardiac apex.'], fallback: 'The left ventricle has a substantially thicker myocardial wall than the right because systemic vascular resistance is higher than pulmonary resistance.' },
    { title: 'Pulmonary pathway', prompt: 'Select the right ventricle and pulmonary trunk as the two structures initiating pulmonary circulation.', targetIds: ['right-ventricle', 'pulmonary-artery'], hints: ['Start with the chamber receiving blood from the right atrium.', 'Then select the vessel leaving through the pulmonary valve.'], fallback: 'The right ventricle ejects into the pulmonary trunk, which bifurcates to carry deoxygenated blood to the lungs.' },
  ]),
  brain: makeLessons('brain', [
    { title: 'Executive planning', prompt: 'Select the lobe central to executive function and voluntary motor planning.', targetIds: ['frontal-lobe'], fallback: 'The frontal lobe supports executive control and initiation of voluntary movement.' },
    { title: 'Motor refinement', prompt: 'Identify the structure that refines movement timing and motor learning.', targetIds: ['cerebellum'], fallback: 'The cerebellum compares intended and performed movement to support coordination and adaptation.' },
  ]),
  lungs: makeLessons('lungs', [
    { title: 'Conducting airway', prompt: 'Select the airway supported by cartilaginous rings.', targetIds: ['trachea'], fallback: 'The trachea conducts air and remains patent through C-shaped cartilage supports.' },
    { title: 'Lobar comparison', prompt: 'Select both marked lung lobes.', targetIds: ['right-upper-lobe', 'left-lower-lobe'], fallback: 'The marked lobes demonstrate the asymmetric lobar organization of the right and left lungs.' },
  ]),
  kidney: makeLessons('kidney', [
    { title: 'Filtration region', prompt: 'Select the region containing glomeruli and convoluted tubules.', targetIds: ['renal-cortex'], fallback: 'The renal cortex contains renal corpuscles where plasma ultrafiltration begins.' },
    { title: 'Urine collection', prompt: 'Identify the funnel that collects urine before the ureter.', targetIds: ['renal-pelvis'], fallback: 'The renal pelvis receives urine from the calyces and narrows into the ureter.' },
  ]),
  eye: makeLessons('eye', [
    { title: 'Primary refraction', prompt: 'Select the transparent surface providing most refractive power.', targetIds: ['cornea'], fallback: 'The air-cornea interface accounts for most optical refraction in the eye.' },
    { title: 'Neural output', prompt: 'Identify the structure carrying retinal ganglion-cell axons to the brain.', targetIds: ['optic-nerve'], fallback: 'The optic nerve is the neural output pathway from the retina.' },
  ]),
  liver: makeLessons('liver', [
    { title: 'Major lobe', prompt: 'Select the largest anatomical lobe of the liver.', targetIds: ['right-lobe'], fallback: 'The right lobe is the largest anatomical division of the liver.' },
    { title: 'Portal gateway', prompt: 'Identify the gateway for the portal vein, hepatic artery, and bile ducts.', targetIds: ['porta-hepatis'], fallback: 'The porta hepatis transmits the portal triad and associated lymphatic and neural structures.' },
  ]),
  'nervous-system': makeLessons('nervous-system', [
    { title: 'Central pathway', prompt: 'Select the CNS structure containing long tracts and segmental reflex circuits.', targetIds: ['spinal-cord'], fallback: 'The spinal cord connects brain and peripheral pathways and integrates many reflexes.' },
    { title: 'Peripheral pathway', prompt: 'Identify the large nerve serving the posterior thigh and much of the leg.', targetIds: ['sciatic-nerve'], fallback: 'The sciatic nerve is a major peripheral nerve formed by lumbosacral roots.' },
  ]),
  skin: makeLessons('skin', [
    { title: 'Surface barrier', prompt: 'Select the avascular keratinized epithelial layer.', targetIds: ['epidermis'], fallback: 'The epidermis forms the skin surface barrier and receives nutrients by diffusion.' },
    { title: 'Supporting layers', prompt: 'Select the dermis and hypodermis together.', targetIds: ['dermis', 'hypodermis'], fallback: 'The dermis provides vascular connective-tissue support while the hypodermis anchors skin to deeper structures.' },
  ]),
  anatomy: makeLessons('anatomy', [
    { title: 'Renal orientation', prompt: 'In the organs layer, select the left kidney.', targetIds: ['anatomy:organs:kidney-left'], fallback: 'The kidneys are paired retroperitoneal organs that filter plasma and regulate fluid balance.' },
    { title: 'Abdominal relationships', prompt: 'Select both the liver and left kidney.', targetIds: ['anatomy:organs:liver', 'anatomy:organs:kidney-left'], fallback: 'The liver occupies the right upper abdomen while the left kidney lies retroperitoneally on the opposite side.' },
  ]),
  'digestive-system': makeLessons('digestive-system', [
    { title: 'Bolus transport', prompt: 'Select the conduit carrying a swallowed bolus toward the stomach.', targetIds: ['esophagus'], fallback: 'Coordinated peristalsis moves a bolus through the esophagus.' },
    { title: 'Digestion to absorption', prompt: 'Select the stomach and small intestine in physiological sequence.', targetIds: ['stomach', 'small-intestine'], fallback: 'The stomach creates chyme; the small intestine then performs most enzymatic digestion and absorption.' },
  ]),
}

export const lessons = Object.values(lessonsByModel).flat()
export const lessonsForModel = (modelId: string) => lessonsByModel[modelId] ?? []
